// This file was automatically generated by noise-serde-lib.
import Foundation
import NoiseBackend
import NoiseSerde

public struct TaskItem: Identifiable, Readable, Sendable, Writable {
  public let id: UVarint
  public let listId: UVarint
  public let text: String
  public let dueDate: String?
  public let completed: Bool
  public let createdAt: Varint
  public let listName: String

  public init(
    id: UVarint,
    listId: UVarint,
    text: String,
    dueDate: String?,
    completed: Bool,
    createdAt: Varint,
    listName: String
  ) {
    self.id = id
    self.listId = listId
    self.text = text
    self.dueDate = dueDate
    self.completed = completed
    self.createdAt = createdAt
    self.listName = listName
  }

  public static func read(from inp: InputPort, using buf: inout Data) -> TaskItem {
    return TaskItem(
      id: UVarint.read(from: inp, using: &buf),
      listId: UVarint.read(from: inp, using: &buf),
      text: String.read(from: inp, using: &buf),
      dueDate: String?.read(from: inp, using: &buf),
      completed: Bool.read(from: inp, using: &buf),
      createdAt: Varint.read(from: inp, using: &buf),
      listName: String.read(from: inp, using: &buf)
    )
  }

  public func write(to out: OutputPort) {
    id.write(to: out)
    listId.write(to: out)
    text.write(to: out)
    dueDate.write(to: out)
    completed.write(to: out)
    createdAt.write(to: out)
    listName.write(to: out)
  }
}

public struct TodoList: Readable, Sendable, Writable {
  public let id: UVarint
  public let name: String

  public init(
    id: UVarint,
    name: String
  ) {
    self.id = id
    self.name = name
  }

  public static func read(from inp: InputPort, using buf: inout Data) -> TodoList {
    return TodoList(
      id: UVarint.read(from: inp, using: &buf),
      name: String.read(from: inp, using: &buf)
    )
  }

  public func write(to out: OutputPort) {
    id.write(to: out)
    name.write(to: out)
  }
}

public final class Backend: Sendable {
  let impl: NoiseBackend.Backend!

  init(withZo zo: URL, andMod mod: String, andProc proc: String) {
    impl = NoiseBackend.Backend(withZo: zo, andMod: mod, andProc: proc)
  }

  public func addList(named name: String) -> Future<String, UVarint> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0000).write(to: out)
        name.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> UVarint in
        return UVarint.read(from: inp, using: &buf)
      }
    )
  }

  public func addList(named name: String) async throws -> UVarint {
    return try await FutureUtil.asyncify(addList(named: name))
  }

  public func addTask(inList listId: UVarint, withText text: String, dueOn dueDate: String?) -> Future<String, Bool> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0001).write(to: out)
        listId.write(to: out)
        text.write(to: out)
        dueDate.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Bool in
        return Bool.read(from: inp, using: &buf)
      }
    )
  }

  public func addTask(inList listId: UVarint, withText text: String, dueOn dueDate: String?) async throws -> Bool {
    return try await FutureUtil.asyncify(addTask(inList: listId, withText: text, dueOn: dueDate))
  }

  public func closeDatabase() -> Future<String, Void> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0002).write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Void in }
    )
  }

  public func closeDatabase() async throws -> Void {
    return try await FutureUtil.asyncify(closeDatabase())
  }

  public func connectToDatabase(atPath path: String) -> Future<String, Bool> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0003).write(to: out)
        path.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Bool in
        return Bool.read(from: inp, using: &buf)
      }
    )
  }

  public func connectToDatabase(atPath path: String) async throws -> Bool {
    return try await FutureUtil.asyncify(connectToDatabase(atPath: path))
  }

  public func deleteList(forId id: UVarint) -> Future<String, Bool> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0004).write(to: out)
        id.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Bool in
        return Bool.read(from: inp, using: &buf)
      }
    )
  }

  public func deleteList(forId id: UVarint) async throws -> Bool {
    return try await FutureUtil.asyncify(deleteList(forId: id))
  }

  public func deleteTask(forId id: UVarint) -> Future<String, Bool> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0005).write(to: out)
        id.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Bool in
        return Bool.read(from: inp, using: &buf)
      }
    )
  }

  public func deleteTask(forId id: UVarint) async throws -> Bool {
    return try await FutureUtil.asyncify(deleteTask(forId: id))
  }

  public func editTask(forId id: UVarint, inList listId: UVarint, withText text: String, dueOn dueDate: String?) -> Future<String, Bool> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0006).write(to: out)
        id.write(to: out)
        listId.write(to: out)
        text.write(to: out)
        dueDate.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Bool in
        return Bool.read(from: inp, using: &buf)
      }
    )
  }

  public func editTask(forId id: UVarint, inList listId: UVarint, withText text: String, dueOn dueDate: String?) async throws -> Bool {
    return try await FutureUtil.asyncify(editTask(forId: id, inList: listId, withText: text, dueOn: dueDate))
  }

  public func formatDateForDisplay(for s: String) -> Future<String, String> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0007).write(to: out)
        s.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> String in
        return String.read(from: inp, using: &buf)
      }
    )
  }

  public func formatDateForDisplay(for s: String) async throws -> String {
    return try await FutureUtil.asyncify(formatDateForDisplay(for: s))
  }

  public func getAllLists() -> Future<String, [TodoList]> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0008).write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> [TodoList] in
        return [TodoList].read(from: inp, using: &buf)
      }
    )
  }

  public func getAllLists() async throws -> [TodoList] {
    return try await FutureUtil.asyncify(getAllLists())
  }

  public func getCurrentDbPath() -> Future<String, String?> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0009).write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> String? in
        return String?.read(from: inp, using: &buf)
      }
    )
  }

  public func getCurrentDbPath() async throws -> String? {
    return try await FutureUtil.asyncify(getCurrentDbPath())
  }

  public func getDefaultDbPath() -> Future<String, String> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x000a).write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> String in
        return String.read(from: inp, using: &buf)
      }
    )
  }

  public func getDefaultDbPath() async throws -> String {
    return try await FutureUtil.asyncify(getDefaultDbPath())
  }

  public func getDefaultList() -> Future<String, TodoList?> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x000b).write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> TodoList? in
        return TodoList?.read(from: inp, using: &buf)
      }
    )
  }

  public func getDefaultList() async throws -> TodoList? {
    return try await FutureUtil.asyncify(getDefaultList())
  }

  public func getTasksByView(forView view: String, inList listId: UVarint?, matching keyword: String?) -> Future<String, [TaskItem]> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x000c).write(to: out)
        view.write(to: out)
        listId.write(to: out)
        keyword.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> [TaskItem] in
        return [TaskItem].read(from: inp, using: &buf)
      }
    )
  }

  public func getTasksByView(forView view: String, inList listId: UVarint?, matching keyword: String?) async throws -> [TaskItem] {
    return try await FutureUtil.asyncify(getTasksByView(forView: view, inList: listId, matching: keyword))
  }

  public func installCallback(internalWithId id: UVarint, andAddr addr: Varint) -> Future<String, Void> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x000d).write(to: out)
        id.write(to: out)
        addr.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Void in }
    )
  }

  public func installCallback(internalWithId id: UVarint, andAddr addr: Varint) async throws -> Void {
    return try await FutureUtil.asyncify(installCallback(internalWithId: id, andAddr: addr))
  }

  public func isDbConnected() -> Future<String, Bool> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x000e).write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Bool in
        return Bool.read(from: inp, using: &buf)
      }
    )
  }

  public func isDbConnected() async throws -> Bool {
    return try await FutureUtil.asyncify(isDbConnected())
  }

  public func isToday(date s: String) -> Future<String, Bool> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x000f).write(to: out)
        s.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Bool in
        return Bool.read(from: inp, using: &buf)
      }
    )
  }

  public func isToday(date s: String) async throws -> Bool {
    return try await FutureUtil.asyncify(isToday(date: s))
  }

  public func parseDateString(for s: String) -> Future<String, String?> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0010).write(to: out)
        s.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> String? in
        return String?.read(from: inp, using: &buf)
      }
    )
  }

  public func parseDateString(for s: String) async throws -> String? {
    return try await FutureUtil.asyncify(parseDateString(for: s))
  }

  public func searchTasks(for keyword: String) -> Future<String, [TaskItem]> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0011).write(to: out)
        keyword.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> [TaskItem] in
        return [TaskItem].read(from: inp, using: &buf)
      }
    )
  }

  public func searchTasks(for keyword: String) async throws -> [TaskItem] {
    return try await FutureUtil.asyncify(searchTasks(for: keyword))
  }

  public func toggleTaskCompleted(forId id: UVarint) -> Future<String, Bool> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0012).write(to: out)
        id.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Bool in
        return Bool.read(from: inp, using: &buf)
      }
    )
  }

  public func toggleTaskCompleted(forId id: UVarint) async throws -> Bool {
    return try await FutureUtil.asyncify(toggleTaskCompleted(forId: id))
  }

  public func updateList(forId id: UVarint, toName name: String) -> Future<String, Bool> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0013).write(to: out)
        id.write(to: out)
        name.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Bool in
        return Bool.read(from: inp, using: &buf)
      }
    )
  }

  public func updateList(forId id: UVarint, toName name: String) async throws -> Bool {
    return try await FutureUtil.asyncify(updateList(forId: id, toName: name))
  }
}
